# Terraform Workflow for GitHub Actions
name: 'Terraform AWS S3 Static Website Deploy'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Upload static files to S3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 botocore ansible
          ansible-galaxy collection install amazon.aws

      - name: Run Ansible Playbook to upload website files
        run: |
          ansible-playbook ../ansible/upload_website.yml
        env:
          TF_VAR_bucket_name: ${{ secrets.STATIC_WEBSITE_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}